<div class="container-fluid">
    <div class="row">
        <div class="col md">'
            <div class="card" style="width: 25rem; margin: auto; float: none;">
                <div class="card-body">
                    Cadastrar
                    <hr>
                    <form action="/registrar" method="post">
                        <div class="mb-3">
                            <label class="form-label">Nome:</label>
                            <input class="form-control" type="text" name="nome" placeholder="João">
                        </div>
                        <div class="mb-3">
                            <label class="form-label">E-mail</label>
                            <input class="form-control" type="text" name="email" placeholder="example@example.com">
                        </div>
                        <div class="mb-3">
                            <label>Senha</label>
                            <input class="form-control" type="password" name="senha" placeholder="******">
                        </div>
                        <button class="btn btn-primary btn-block mt-4" type="submit">Gravar</button>
                    </form>
                </div>
            </div>
            <br>
        </div>
    </div>
</div>