<div class="container my-3">
	<div class="card" style="width: 25rem; margin: auto; float: none;">
		<div class="card-body">
            Login
            <hr>
			<form action="/autenticar" method="post">
                <div class="mb-3">
                    <label class="form-label">E-mail</label>
                    <input class="form-control" type="text" name="email" placeholder="example@example.com">
                </div>
                <div class="mb-3">
                    <label>Senha</label>
                    <input class="form-control" type="password" name="senha" placeholder="******">
                </div>
                <button class="btn btn-primary btn-block mt-4" type="submit">Entrar</button>
                <div class="my-3">
                    Não possui cadastro?
                    <a href="/cadastrar">clique aqui para cadastrar</a>
                </div>
            </form>
		</div>
	</div>
</div>