<h1>Home</h1>
<div class="row">
    <div class="col-md-12 my-5">
        <div class="row">
            <div class="col">
                <div class="card p-3">
                    <form action="/postagem?pagina=feed" method="post">
                        <textarea class="form-control" name="postagem" rows="1"></textarea>
                        <div class="mt-2 d-flex">
                            <button class="btn btn-primary">Postar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <?php foreach($this->view->postagens as $indice => $postagem){ ?>
        <div class="row">
            <div class="col mt-3">
                <div class="card p-3">
                    <p><strong><?= $postagem['nome'] ?></strong><small> <span class="text text-muted">- <?=$postagem['data']?></span></small></p>
                    <hr class="mt-0">
                    <p><?=$postagem['postagem']?></p>
                    <div class="d-flex mt-2">
                        <button class="btn btn-primary">Remover</button>
                    </div>
                </div>
            </div>
        </div>
        <?php } ?>
        
    </div>
</div>