<div class="row">
    <div class="col mt-3">
        <div class="card p-2">
            <h6 class="pl-3">Fotos</h6>
            <hr class="mt-0 mb-3">
            <div class="row row-cols-1 row-cols-md-2">
                <div class="col mb-2">
                    <div class="amigos card">
                        <a href="">
                            <img src="images/usuario.svg" class="rounded border img">
                            <small class="text-dark">Nome usuário</small>
                        </a>
                    </div>
                </div>
                <div class="col mb-2">
                    <div class="amigos card">
                        <a href="">
                            <img src="images/usuario.svg" class="rounded border img">
                            <small class="text-dark">Nome usuário</small>
                        </a>
                    </div>
                </div>
                <div class="col mb-2">
                    <div class="amigos card">
                        <a href="">
                            <img src="images/usuario.svg" class="rounded border img">
                            <small class="text-dark">Nome usuário</small>
                        </a>
                    </div>
                </div>
                <div class="col mb-2">
                    <div class="amigos card">
                        <a href="">
                            <img src="images/usuario.svg" class="rounded border img">
                            <small class="text-dark">Nome usuário</small>
                        </a>
                    </div>
                </div>
            </div>         
        </div>
    </div>
</div>