<div class="row px-3 mb-3">
    <div class="col-md-4 mt-3">
        <div class="card pt-2 px-2">
            <h6 class="pl-3">Amigos</h6>
            <hr class="mt-0 mb-1">
            <div class="row py-2">
                <div class="col-4 text-wrap">
                    <a href="" class="text-decoration-none">
                        <img src="images/usuario.svg" class="rounded border">
                        <small class="text-dark">Nome usuário</small>
                    </a>
                </div>
                <div class="col-4">
                    <a href="" >
                        <img src="images/usuario.svg" class="rounded border">
                        <small class="text-dark">Nome usuário</small>
                    </a>
                </div>
                <div class="col-4">
                    <a href="">
                        <img src="images/usuario.svg" class="rounded border">
                        <small class="text-dark">Nome usuário</small>
                    </a>
                </div>
            </div>
            <div class="row py-2">
            <div class="col-4 text-wrap">
                    <a href="" class="text-decoration-none">
                        <img src="images/usuario.svg" class="rounded border">
                        <small class="text-dark">Nome usuário</small>
                    </a>
                </div>
                <div class="col-4">
                    <a href="" >
                        <img src="images/usuario.svg" class="rounded border">
                        <small class="text-dark">Nome usuário</small>
                    </a>
                </div>
                <div class="col-4">
                    <a href="">
                        <img src="images/usuario.svg" class="rounded border">
                        <small class="text-dark">Nome usuário</small>
                    </a>
                </div>
            </div>
            <div class="row py-2">
            <div class="col-4 text-wrap">
                    <a href="" class="text-decoration-none">
                        <img src="images/usuario.svg" class="rounded border">
                        <small class="text-dark">Nome usuário</small>
                    </a>
                </div>
                <div class="col-4">
                    <a href="" >
                        <img src="images/usuario.svg" class="rounded border">
                        <small class="text-dark">Nome usuário</small>
                    </a>
                </div>
                <div class="col-4">
                    <a href="">
                        <img src="images/usuario.svg" class="rounded border">
                        <small class="text-dark">Nome usuário</small>
                    </a>
                </div>
            </div>            
        </div>
    </div>
    <div class="col-md-8 mt-3">
        <div class="row">
            <div class="col">
                <div class="card p-2">
                    <h6 >Postagem</h6>
                    <hr class="mt-0 mb-2">
                    <form action="">
                        <textarea class="form-control" name="postagem" rows="1"></textarea>
                        <div class="mt-2 d-flex">
                            <button class="btn btn-primary">Postar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col mt-3">
                <div class="card p-2">
                    <p><strong>Nome usuario</strong><small> <span class="text text-muted">- 01/01/2020 19:00</span></small></p>
                    <hr class="mt-0">
                    <p>Postagem</p>
                    <div class="d-flex mt-2">
                        <button class="btn btn-primary">Remover</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col mt-3">
                <div class="card p-2">
                    <p><strong>Nome usuario</strong><small> <span class="text text-muted">- 01/01/2020 19:00</span></small></p>
                    <hr class="mt-0">
                    <p>Postagem</p>
                    <div class="d-flex mt-2">
                        <button class="btn btn-primary">Remover</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>